### ISSUE TITLE
provide way to print directory without doing anything else

### ISSUE THREAD

**Issue by rogpeppe** [rogpeppe/gohack#14]
It would be useful to be able to print the gohack directory for a module
without actually making any changes.

Perhaps:

    gohack -p modulepath

would print the directory for *modulepath*.
With no arguments, -p could print the directories for all the modules in the current module that have gohack directories.

**Comment by myitcv** [comment]
How about following the go list model?

**Comment by rogpeppe** [comment]
`gohack status` prints out the current gohack status including directory, which is probably good enough for now.
