### ISSUE TITLE
multiple subcommands

### ISSUE THREAD

**Issue by rogpeppe** [rogpeppe/gohack#19]
As the amount of functionality grows, it seems like we should consider having subcommands.

A possible set of commands:

     gohack get [-vcs] [-u] [-f] [module...]

Get gets the modules at the current version and adds replace statements to the go.mod file if they're not already replaced.
If the `-u` flag is provided, the source code will also be updated to the current version if it's clean.
If the `-f` flag is provided with `-u`, the source code will be updated even if it's not clean.
If the `-vcs` flag is provided, it also checks out VCS information for the modules. If the modules were already gohacked in non-VCS mode, gohack switches them to VCS mode, preserving any changes made (this might result in the directory moving).

With no module arguments and the `-u` flag, it will try to update all currently gohacked modules.

    gohack diff module

Diff prints (in git style) changes that have been made to the module since it was checked out.

    gohack rm [-f] module...

Rm removes the gohack directory if it is clean and then runs `gohack undo`. If the `-f` flag is provided, the directory is removed even if it's not clean.

     gohack undo [module...]

Undo removes the replace statements for the modules. If no modules are provided, it will undo all gohack replace statements. The gohack module directories are unaffected.

    gohack dir [-vcs] [module...]

Dir prints the gohack module directory names for the given modules. If no modules are given, all the currently gohacked module directories are printed. If the `-vcs` flag is provided, the directory to be used in VCS mode is printed. Unlike the other subcommands, the modules don't need to be referenced by the current module.

**Comment by mvdan** [comment]
Overall agree that we need subcommands. Some ideas that come to mind...

* perhaps `gohack replace` instead of `gohack get`? though either seems intuitive enough to me
* why would I use `gohack diff module` instead of just `cd $GOHACK/$module; git diff`? presumably because it's possible to make a copy of a module without VCS info?
* `gohack diff` should probably get the more common/useful flags from `diff` or `git diff`. I personally use `git diff --stat` all the time, for example, although it may not make sense outside of VCS.
* instead of having both `undo` and `rm`, why not have just `undo` with a flag like `-rm`?

Would need to start using the subcommands to be able to give better input :)

**Comment by rogpeppe** [comment]
Thanks for the feedback.

> perhaps `gohack replace` instead of `gohack get`? though either seems intuitive enough to me

I've been toying with that name too. I think I'll stick with get for now as it's shorter and the semantics are pretty similiar to those of `go get` (apart from the replacement clause bit of course).

> why would I use `gohack diff module` instead of just `cd $GOHACK/$module; git diff`? presumably because it's possible to make a copy of a module without VCS info?

Yup, that's exactly the reason.

> `gohack diff` should probably get the more common/useful flags from `diff` or `git diff`. I personally use `git diff --stat` all the time, for example, although it may not make sense outside of VCS.

Huh, I never knew about `git diff --stat` - I just do `git diff | diffstat` (or more often, `git show $commit | diffstat`). We can add more flags later to taste.

> instead of having both `undo` and `rm`, why not have just `undo` with a flag like `-rm`?

Yeah, I'd also been toying with that idea. I think you're probably right - I'll go with that for now.

**Comment by rogpeppe** [comment]
Fixed by #20
