### ISSUE TITLE
cannot update VCS dir for github.com/labstack/echo: error: pathspec 'v3.2.1+incompatible' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by wangyun** [rogpeppe/gohack#21]
when run
gohack github.com/labstack/echo

it show this error message:
creating github.com/labstack/echo@v3.2.1+incompatible
cannot update VCS dir for github.com/labstack/echo: error: pathspec 'v3.2.1+incompatible' did not match any file(s) known to git.
all modules failed; not replacing anything

**Comment by wangyun** [comment]
Yes, I think this issue has been fixed, thanks.

Before update gohack:
$ gohack get github.com/labstack/echo
module "get" does not appear to be in use
creating github.com/labstack/echo@v3.2.1+incompatible
cannot update VCS dir for github.com/labstack/echo: error: pathspec 'v3.2.1+incompatible' did not match any file(s) known to git.
all modules failed; not replacing anything

After I update gohack to the latest master
$ go get -u github.com/rogpeppe/gohack@master
$ gohack get github.com/labstack/echo
github.com/labstack/echo => /home/wangyun/gohack/github.com/labstack/echo

$ cat go.mod
module testgohack

require (
	github.com/kr/pty v1.1.3 // indirect
	github.com/labstack/echo v3.2.1+incompatible
	github.com/labstack/gommon v0.2.7 // indirect
	github.com/mattn/go-colorable v0.0.9 // indirect
	github.com/mattn/go-isatty v0.0.4 // indirect
	github.com/rogpeppe/gohack v0.0.0-20181005082049-9c9664a5b5fe // indirect
	github.com/valyala/bytebufferpool v1.0.0 // indirect
	github.com/valyala/fasttemplate v0.0.0-20170224212429-dcecefd839c4 // indirect
	golang.org/x/crypto v0.0.0-20181001203147-e3636079e1a4 // indirect
	golang.org/x/tools v0.0.0-20181004163742-59602fdee893 // indirect
)

replace github.com/labstack/echo => /home/wangyun/gohack/github.com/labstack/echo

**Comment by rogpeppe** [comment]
thanks for the info.
