### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by mvdan** [rogpeppe/gohack#3]
Particularly to check that `go test ./...` is happy, including vet. If we want this to be more than a one-man project, CI will be useful.

Happy to enable the repo on Travis and send a PR with the yaml file if @rogpeppe agrees. We can use go1.11beta3 for now.

**Comment by rogpeppe** [comment]
Seems like an excellent idea to me.

**Comment by rogpeppe** [comment]
Fixed by #26
