### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mvdan** [rogpeppe/gohack#4]
I think that, for this kind of tool, the best approach would be shell-like tests. For example:

* create a new module in a temporary directory
* add a main.go with a `foo/bar` dependency
* run `go build` to update `go.mod`
* run `gohack foo/bar`
* check that the replace directive is there
* run `gohack -u foo/bar`
* check that the replace directive is gone

**Comment by mvdan** [comment]
We could copy the new `cmd/go` test language, which I think is very cool. See `src/cmd/go/testdata/script/README` for how it works.

**Comment by rogpeppe** [comment]
Fixed by #24
