### ISSUE TITLE
gohack does not allow relative directories in GOHACK env var.

### ISSUE THREAD

**Issue by davidovich** [rogpeppe/gohack#44]
We want to be able to set GOHACK to a relative dir, say `./`. But this is not possible at the moment as the initial `./` is removed in the replace directive, creating a broken replacement line for go:

```
replacement module without version must be directory path (rooted or starting with ./ or ../)
```

We can work around the problem by manually prefixing the replacement with `./`.

We like the relative path use-case, because it allows enhanced interop in WSL, when the path is on a shared Windows mount (/mnt/c/...), Windows go tools can interpret the same (relative) path as the WSL go tools. With absolute paths, Windows tools obviously cannot interpret the `/mnt/c/...` mount.

This is somewhat related to #27.

**Comment by davidovich** [comment]
Friendly ping; any news on this @rogpeppe ? Are you open to a PR for this issue ?

**Comment by myitcv** [comment]
> Are you open to a PR for this issue ?

Yes, very much so :)
