### ISSUE TITLE
Idea: flag for "fork" remote

### ISSUE THREAD

**Issue by ldelossa** [rogpeppe/gohack#57]
So the workflow I just used was the following:

* use gohack to pull down depedenency I want to add log statements too or changes
* cd int ~/gohack/github.com/ldelossa/repo
* added a remote called "fork" which points to my fork of github.com/ldelossa/repo
* hacked on code till I got what I wanted, pushed branch to my fork
* open PR of fork with original repo.

Obviously the fork will need to be setup everytime we run GoHack. Curious if you think it's a good idea to add a "remote" or "fork" cli flag to gohack which setups a remote fork to push your changes too in an automated fashion. If so I'd like to take a stab at this PR.

**Comment by mvdan** [comment]
Assuming you're talking about github, I tend to just do `hub fork`, which does the actual forking as well as configuring the git remote. See https://github.com/github/hub.

That's easy to install and type, so I think it's fine to leave it separate from gohack.

**Comment by ldelossa** [comment]
When i first opened this i thought Github was the only CVS supported. I agree when your statement. Thanks for the feedback.
