### ISSUE TITLE
cannot get module info

### ISSUE THREAD

**Issue by gadelkareem** [rogpeppe/gohack#70]
I am getting error 
```
$ gohack get -vcs gopkg.in/danilopolani
cannot get module info: go list -m: can't compute 'all' using the vendor directory
	(Use -mod=mod or -mod=readonly to bypass.)
```

**Comment by rogpeppe** [comment]
Could you provide a minimal reproducible example here, please? Otherwise it's very hard to know what's going on. For example, I can't tell if you've got a `go.mod` file.

**Comment by gadelkareem** [comment]
Here is a an example repo https://github.com/gadelkareem/test
Just clone it and do a `go mod vendor` then `gohack get -vcs gopkg.in/danilopolani` and you should see the error.

**Comment by jc-dgit** [comment]
@gadelkareem Just to point out, the repo you're pointing to is empty.  No code in it whatsoever.

**Comment by gadelkareem** [comment]
I think this is not relevant anymore, thanks!
