### ISSUE TITLE
support linked file in gohack directory

### ISSUE THREAD

**Issue by zhyon404** [rogpeppe/gohack#72]
i want to place my local change somewhere other than $HOME/gohack, so i create a linked file under it.
it reports error `already exists; not overwriting` when running `gohack get`.

could linked file be treated like a real directory?

**Comment by myitcv** [comment]
Using a symlink for the `gohack` works just fine. 

```
export GOPATH=$(mktemp -d)
cd $(mktemp -d)
unset GOHACK
go mod init example.com/hello
go get gopkg.in/yaml.v2
mkdir $HOME/asdf
ln -s $HOME/asdf $HOME/gohack
gohack get gopkg.in/yaml.v2
find $HOME/asdf
```

You could alternatively set the `GOHACK` environment variable to the target directory you want. 

Please shout if you are still having problems.
